### ISSUE TITLE
Type stubs for autocompletion

### ISSUE THREAD

**Issue by srittau** [srittau/type-stub-pep#11]
We should probably mention that type stubs are also applicable for autocompletion. IIRC there was a discussion recently regarding this and `unittest.mock.Mock`. In my opinion it is a good idea to recommend including fields and methods, even if a type checker would not necessarily need them (e.g. because of `__getattr__`) for the use of autocompleters.

**Comment by rchen152** [comment]
I'm missing the context on autocompletion, but I agree that the presence of `__getattr__` shouldn't be a reason to omit more precise information. In my mental model, `__getattr__` is a fallback that only comes into play when an attribute isn't found in the rest of the stub.

**Comment by srittau** [comment]
Closed in #16.
