### ISSUE TITLE
Recommend style for global attributes

### ISSUE THREAD

**Issue by srittau** [srittau/type-stub-pep#13]
If I understand correctly, these two module-level definitions are equivalent:

```python
GLOBAL1: int = ...
GLOBAL2: int
```

I think we should recommend one of the two in the style guide for consistency. I'd prefer the latter variant, as it is shorter and the default does not serve much purpose.

**Comment by JelleZijlstra** [comment]
I agree. There's also `GLOBAL1 = 0`, which we should also discourage.

**Comment by Solumin** [comment]
I second `GLOBAL2: int` as the recommended style. Type stubs don't care about default values, so there's no reason to include them.

I do see an argument for including `= ...` so the statement looks like a variable assignment. But I don't think it adds any value and is purely boilerplate.

**Comment by rchen152** [comment]
I third (is that a thing?) `GLOBAL2: int`. Why only global attributes? I think we should make the same recommendation for class attributes.

**Comment by srittau** [comment]
Someone correct me if I am wrong, because I am not terribly sure myself, but I think this marks a "regular" instance attribute (i.e. one that is set in `__init__`):

```python
class Foo:
    bar: int
```

While this is supposed to mark an instance attribute with a class default:

```python
class Foo:
    bar: int = ...

# Implementation
class Foo:
    bar = 42
    def __init__(self):
        self.bar = 99
```



I also don't think that this currently makes a difference with any type checker.

**Comment by rchen152** [comment]
I wasn't aware of this difference. I can confirm that pytype doesn't distinguish between class and instance attributes in a pyi file, unless the attribute contains a typevar.

**Comment by srittau** [comment]
This has been added to the Wiki.
