### ISSUE TITLE
Recommend using `str` over `Text` for Python 3 only stubs?

### ISSUE THREAD

**Issue by srittau** [srittau/type-stub-pep#14]
What is everyone's opinion on this? In Python 3 stubs or Python 3 branches using `Text` over `str` adds an unneeded level of indirection, in my opinion.

**Comment by JelleZijlstra** [comment]
I agree with using `str`. One exception could be that if you intend your stub to be merged with a Python 2 stub later, or wish to minimize differences with a Python 2 stub, it makes sense to use `Text`. But those situations are rare enough that they don't need special mention.

**Comment by Solumin** [comment]
The `typing.Text` documentation says:

> Text is an alias for str. It is provided to supply a forward compatible path for Python 2 code: in Python 2, Text is an alias for unicode.
> 
> Use Text to indicate that a value must contain a unicode string in a manner that is compatible with both Python 2 and Python 3

If a stub is Python 3-only, then using `str` over `Text` makes sense. So I agree with recommending `str` over `Text` for Python 3-only stubs, emphasizing that `Text` should be used for 2and3 compatibility.

**Comment by srittau** [comment]
Thanks! I have added the recommendation to the PEP Content Wiki page.
