### ISSUE TITLE
Distribution: Typeshed

### ISSUE THREAD

**Issue by srittau** [srittau/type-stub-pep#23]
I'd like to include a section about typeshed, especially the third-party packages project (python/typeshed#2491). What does everyone think?

**Comment by Solumin** [comment]
Sure! Here's a good start:

> ## Typeshed
> The [typeshed repository](https://github.com/python/typeshed/) is a collection of type stub files for the Python standard library, Python builtins and various third-party packages. It supports Python version 2.7 and 3.4 and up. Type stubs in typeshed are tested against multiple type checkers to ensure compatibility.

I'll leave the contented related to python/typeshed#2491 up to you, since you're more familiar with it.

**Comment by srittau** [comment]
I am going to close this, since we actually have a sentence about typeshed in the "Distribution" section.
