### ISSUE TITLE
Tuple-based Version Checks

### ISSUE THREAD

**Issue by Solumin** [srittau/type-stub-pep#26]
This came up when writing #25. [PEP 484][1] allows version checks to index into `sys.version_info`:

```
if sys.version_info[0] >= 3:
  ...

# Presumably, major and minor are also fine:
if sys.version_info.major >= 3:
  ...
```

Since `sys.version_info` is a tuple, these version checks can be tuple comparisons instead:

```
if sys.version_info >= (3,):
  ...
```

Do we want to encourage one style over the other? Personally, I prefer tuple checks.

- They look more like version numbers, so the check is easier to grok.
- They're the only way that makes sense when checking a minor version. (`sys.version_info >= (3, 5)` for example)

I don't see any particular cons to encouraging tuple checks over index checks. A [quick glance through typeshed][2] suggests that most type stub files in that repository use tuple checks already.

Any thoughts?

[1]: https://www.python.org/dev/peps/pep-0484/#version-and-platform-checking
[2]: https://github.com/python/typeshed/search?q=%22if+sys.%22&unscoped_q=%22if+sys.%22

**Comment by srittau** [comment]
I guess if non-tuple checks are allowed per PEP 484, they should be supported in stubs, but we can (and should) recommend tuple checks. As I noted in the review, maybe we should put what is allowed in the "supported constructs" section and recommend to use tuple-based checks in the style guide.

**Comment by rchen152** [comment]
I think we can close this, since Teddy already has a PR.
