### ISSUE TITLE
Supported Constructs: Integrate PEP 570

### ISSUE THREAD

**Issue by srittau** [srittau/type-stub-pep#35]

**Comment by Solumin** [comment]
@JelleZijlstra pointed out that due to changes in how typed-ast is being developed, mypy may not support this syntax when run under < 3.8.

**Comment by Solumin** [comment]
As per our current draft, in the Syntax section: `[Type stubs] should be valid according to the latest Python version six months after release at the latest, but can start to use features from that release from the release date on.` This PEP probably won't be out before 3.8 is, so stating that type checkers should support PEP 570 in type stubs is consistent with the Syntax section.

**Comment by rchen152** [comment]
Next step is that @srittau will investigate how hard it is to integrate PEP 570 into typed_ast.

**Comment by srittau** [comment]
Scheduled for next tuesday or wednesday.

**Comment by srittau** [comment]
python/typed_ast#125

**Comment by srittau** [comment]
Can't get it to work unfortunately.
