### ISSUE TITLE
Encourage inclusion of docstrings in stubs

### ISSUE THREAD

**Issue by matangover** [srittau/type-stub-pep#38]
Hi all, I have a question/suggestion regarding inclusion of documentation in stubs.

Considering that type stubs 'act as documentation, succinctly explaining the external API of a package', and also that 'IDEs can offer improved autocompletion' using stubs -- why does the PEP discourage inclusion of docstrings? Inclusion of docstrings in stubs would enable IDEs to show better hovers and completions, and would be helpful to a user inspecting a module's API.

If docstrings are not included in stubs, tools providing hovers would still have to inspect and evaluate the code of the actual module (which might be a C module) -- defying the purpose of stubs. PEP 484 says `If a stub file is found the type checker should not read the corresponding "real" module`.

For that matter, typeshed could/should also include docstrings. Tools for automatically generating type stubs should have an option to include docstrings.

In TypeScript, for example, documentation is often included in stubs, and has a [standardized format](https://github.com/Microsoft/tsdoc).

**Comment by srittau** [comment]
Personally, I am in favor of including docstrings in stubs, for the reason you state. But this PEP is mainly intended to document the status quo, which is not to include docstrings.

**Comment by matangover** [comment]
I understand, thanks. Do you know who I should contact to discuss the status quo?

**Comment by srittau** [comment]
Maybe the [typing-sig](https://mail.python.org/mailman3/lists/typing-sig.python.org/) mailing list would be the best place.

**Comment by matangover** [comment]
Thanks, I moved the discussion there.
