### ISSUE TITLE
Using `Literal` in type stubs

### ISSUE THREAD

**Issue by Solumin** [srittau/type-stub-pep#43]
We're all fans of `Literal`. I think it has a ton of value for typing and type stubs, and as such, we should recommend using it. However, it's not applicable for all situations.

For example, in Python 2.7, `six.string_types` is (essentially) `(str, unicode)`. In fact, that's how the [type stubs for six represent it](https://github.com/python/typeshed/blob/master/third_party/2/six/__init__.pyi#L30). (For [Python 3](https://github.com/python/typeshed/blob/master/third_party/3/six/__init__.pyi#L45), it's the one-element tuple `str,`.) With `Literal`, we could instead write `string_types` as `Tuple[Literal[str], Literal[unicode]]`. However, I think `Tuple[Type[str], Type[unicode]]` is better here.

Another example is constants. Let's say some module defines a `DEFAULT_PORT` number: `DEFAULT_PORT = 34377`, maybe. Should the type be `DEFAULT_PORT: int` or `DEFAULT_PORT: Literal[34377]`? What about a `DEFAULT_FILE_MODE = 'wb'`?

The obvious use case for `Literal` is in function signatures, with `open` being the poster child. This is a totally awesome use case and we should encourage it, though I think it's only truly useful for `@overload`ed functions, right?

Here's my recommendation: **We recommend using `Literal` when the literal value of a variable is meaningful for type checkers.** 
- In the examples above, `DEFAULT_PORT` should be an `int`, while `DEFAULT_FILE_MODE` should be `Literal['wb']`. (Assuming `DEFAULT_PORT` doesn't affect the return type of anything it's used in, while `DEFAULT_FILE_MODE` is used in `open` or something.) (I feel this case is contrived, but I don't want to blanket ban `Literal` for constants.)
- In function signatures, use `Literal` only when the parameter's literal value affects the signature of the function. (Note I don't say 'return type' here, because there may be functions where e.g. `a = True` means `b` must be `None`, or something like that.) `open` is a good example, but we could come up with more complicated cases.
- Use `Type` instead of `Literal` for type aliases like `string_types`.
- Above all else, never use bare constants. Use `Literal` instead.

Alternative approaches:
- Use `Literal` wherever. Since the point of this PEP is to bring some manner of consistency to type stubs, I don't particularly think this is valuable.
- Don't mention `Literal` at all. Let [PEP 586](https://www.python.org/dev/peps/pep-0586/) be the guide. This is probably fine, but again, we're trying to bring some consistency -- we should talk about `Literal`.
- Recommend `Literal` _only_ for `@overload`ed functions. I think this is too restrictive.

Thoughts? Other approaches? Better examples?

**Comment by rchen152** [comment]
I'm a little skeptical about mentioning Literal. We obviously don't want to exhaustively mention every typing construct (lots of work, and the PEP would go out of date incredibly quickly), so it seems to me that we should only mention ones for which we have recommendations for stub files that differ from what one would do in source code. In this case, only using Literal when the literal value is meaningful seems more like broadly applicable good advice than anything stub-specific.

**Comment by Solumin** [comment]
That's a good point. Withdrawing my recommendation for now then.

(Part of my original complain about typeshed/type stubs was the use of literal values, so I'm very excited to have `Literal` now. :) )
