### ISSUE TITLE
NamedTuple, TypedDict and Generated Types

### ISSUE THREAD

**Issue by Solumin** [srittau/type-stub-pep#48]
I saw NamedTuple mentioned in the wiki, and I have a couple questions related to it.
Since NamedTuple is in `typing`, we obviously support using it in stub files.
Since TypedDict has been accepted ([PEP 589](1)), it follows that we should allow those
in type stubs too.

We also already have a restriction on decorators. However, decorators are used
to create classes in ways similar to NamedTuple and TypedDict, e.g.
`dataclasses` (part of the std lib now) and `attrs` (a popular third-party
library). How should those be handled in type stubs? Requiring support for
third-party libraries is not the right idea, I think, but `dataclasses` is
at least in the std lib.

The options I see:
1. Allow only those generation methods present in `typing`, using NamedTuple and
TypedDict as examples.

This keeps things much simpler for type checkers. For stubs that use methods
like `dataclasses`, type stub authors can enumerate the fully generated class in
the type stub. This doesn't feel particularly onerous to me, but it does depend
on the generation method.

2. Same as above, but also allowing generation methods in the std lib.

The main issue I see is requiring type checkers to potentially accept a large
number of type generation methods and additional decorators as the std lib grows
over time. It also makes type stubs more "dynamic," in that they in a sense
allow run-time behavior. I think we were trying to avoid this, e.g. by
recommending against literals in type stubs. (NamedTuple and TypedDict exist as
useful exceptions to the general avoidance of runtime behavior.)

3. Allow type generation methods from typing, the std lib and third-party libs.

This might not be as horrible an idea as it sounds, since some type generation
behavior can be described by type annotations. But it does potentially put a
huge burden on type checker developers.

Summary:
1. What language do we have in mind for NamedTuple and TypedDict? In particular,
should we recommend the modern NamedTuple syntax over the function-call syntax
for all type stubs?
2. What type generation methods do we require type checkers to support in type
stubs?

[1] https://www.python.org/dev/peps/pep-0589/

**Comment by JelleZijlstra** [comment]
For (1), I'd favor recommending the class-based NamedTuple and TypedDict syntax. It's much nicer and type checkers already need to be able to parse this syntax in stubs.

For (2), I would actually prefer that we accept `@dataclass` in stubs. It's a standard library feature, so I don't think it's unreasonable to ask type checkers to support it. Writing dataclass stubs manually is of course possible, but it's repetitive and error-prone to have to mention the same types for attributes and `__init__` arguments. Type checkers may choose to also support other similar code generation decorators (such as `attrs`, which mypy has a plugin for), but that should be up to individual type checkers and I'd be OK with disallowing those in typeshed.

**Comment by Solumin** [comment]
I agree with you on (1). I'll draft up some text for that.

**Comment by rchen152** [comment]
Regarding (2): my concern about accepting `@dataclass` in stubs is that it makes the final types less transparent. I agree that manually writing out a dataclass stub is tedious, but a human reader (and a type checker) can look at the stub and know exactly what the class looks like, rather than having to go through the mental gymnastics of reconstructing the `__init__` based on the attributes, figuring out how any keyword arguments to the decorator affect what methods are present, etc. My preference would be to not accept it.

Regardless of what we decide about `@dataclass`, not allowing third-party code generation decorators in typeshed seems reasonable to me.

**Comment by srittau** [comment]
Catching up. Agreed on (1). For (2) I slightly prefer to allow `@dataclass`. From a type stub author and reader's perspective I'd prefer to use `@dataclass`. I personally find the declarative approach easier to write and read than writing out an explicit constructor. On the other hand it means that authors of software using type stubs will need to support them. And in the end, dataclasses are just (semantic?) sugar.

I expect dataclasses to be heavily used in the future. We started using them recently and they are a tremendous tool. But as a compromise, maybe we should leave them out from the first version of the PEP? As it will be informational, I expect this to be a "living" document anyway, and they could be added later.

**Comment by rchen152** [comment]
We concluded that the class-based syntax will be recommended but the function-based one still supported, and `@dataclass` will be allowed. I'm going to close this issue and open separate ones for these two points.
