### ISSUE TITLE
Planning session?

### ISSUE THREAD

**Issue by rchen152** [srittau/type-stub-pep#49]
In two days, it'll be one year from when we started working on this PEP (!), and I'm feeling rather guilty about how slow our progress has been.

I was wondering if folks would be up to scheduling a video chat to talk over the PEP? I'm hoping we could resolve all of the remaining questions/ambiguities/differences of opinion, figure out who's writing what, and set a timeline to hold ourselves to.

**Comment by rchen152** [comment]
Or we could do some sort of group writing session to try to finish everything up in one go? And if we're all working on it together, we can discuss things as they come up in real time. But the time zone differences would make this difficult.

**Comment by srittau** [comment]
I like that proposal (and share the feeling of guilt.) Don't worry about time zones for my sake, we have a good coffee maker in the office. :) My schedule is also fairly open at the moment.

**Comment by rchen152** [comment]
Cool! Seems like the most reasonable time of day would be early morning California/evening in Berlin. On Tuesday and Friday next week, I'm completely free, and on Wednesday and Thursday I'm free until 11am.

@JelleZijlstra @Solumin What are your thoughts?

**Comment by JelleZijlstra** [comment]
I can do Monday, Wednesday, or Thursday before 11 am next week.

**Comment by Solumin** [comment]
I can be available on any of those days too!

**Comment by srittau** [comment]
Let's call it Wednesday (July 24th) then. Time (with timezone please)?

**Comment by rchen152** [comment]
Ah, sorry for not including a timezone. How about 9am PDT on Wednesday the 24th?

**Comment by Solumin** [comment]
Looks like that works for everyone! Awesome.

**Comment by rchen152** [comment]
Sweet! I dumped all of our open issues and PRs and the unfinished sections from the PEP Content wiki page into https://github.com/srittau/type-stub-pep/wiki/Planning-Session, to start a list of possible discussion topics. Please edit as you see fit.

See you all on Wednesday :)

**Comment by rchen152** [comment]
Oh wait, I forgot to ask how we should do the video call. Our conference rooms use Google Hangouts Meet - it looks like if I get everyone's email, I can invite you all to the same calendar event, and then we'll all be able to join the meeting. (The link is https://meet.google.com/iju-pjbz-hmk - I don't know if copying and pasting it works.) Does that work for folks?

**Comment by rchen152** [comment]
Great, that was easy!

**Comment by rchen152** [comment]
Ok, I've shared the planning session notes with all of you and opened issues for everything left to write and one for release planning. Each issue name is prefixed with the name of the section that the content belongs to, to hopefully keep things organized a bit better.
