### ISSUE TITLE
Syntax: stubs can only use syntax up to 3.7 (maybe 3.8)

### ISSUE THREAD

**Issue by rchen152** [srittau/type-stub-pep#53]
Because it's not practical for stubs to always be able to use the syntax of the latest release, we decided to go with a fixed maximum version. Depending on the outcome of https://github.com/srittau/type-stub-pep/issues/35, this will be either 3.7 or 3.8. Stubs can still use features from the latest released version that don't require new syntax.

**Comment by srittau** [comment]
3.7 it is unfortunately.

**Comment by srittau** [comment]
Fixed in #65.
