### ISSUE TITLE
Supported Constructs: module-level asserts

### ISSUE THREAD

**Issue by rchen152** [srittau/type-stub-pep#54]
This needs to be discussed more broadly before we decide whether to include it (and may not need to be resolved before publishing the PEP?). It would be useful to allow module-level assertions of what python versions a stub supports. Example use cases:
* A library is a single module in Python 2 but a package in Python 3 whose `__init__` is largely identical to the Python 2 module. Currently, we need to maintain separate per-version stubs that duplicate definitions. If we could assert in the submodule stubs that they are only available in Python 3, then we could have a single set of stubs.
* A library gains a new submodule in Python 3. Currently, we can't model this (except, again, by copying the entire set of stubs). We could model this by asserting in the submodule that it's Python 3-only.

**Comment by srittau** [comment]
Closing this for now. I still think this is a useful feature, but not part of the status quo we aim to describe.
