### ISSUE TITLE
Release Planning

### ISSUE THREAD

**Issue by rchen152** [srittau/type-stub-pep#55]
- [ ] The draft PEP is finished.
- [ ] All authors have done a final read-through and opened PRs to fix up any last issues.
- [ ] Examples have been tweaked to all follow the same style.
- [ ] The PEP has a core dev sponsor.
- [ ] The PEP has been submitted.
- [ ] The PEP has been posted to typing-sig and python-dev.

**Comment by srittau** [comment]
I just self-assigned myself here, since I put this on the meeting schedule.

**Comment by srittau** [comment]
@rchen152 @JelleZijlstra @Solumin I am sorry for not pushing this to completion last year. I also was under the impression that the PEP was more incomplete than it actually is. I have opened two more PRs (#68, #69) that adds what was missing, according to the open issues. I have opened another PR (#70) about new, currently unsupported features.

I would ask you to quickly scan the PEP for any topics we may have missed or that we may need to add. As a next step, I would do a structure and consistency pass, and then a grammar and typo pass. Then we can have a final sign-off of all authors.

**Comment by rchen152** [comment]
Thanks for picking this up again! I can't think of any missing topics. I noticed that we hadn't mentioned the newest type checker, pyright, so I opened a PR to add it.

**Comment by srittau** [comment]
I went through the whole document again and opened fairly fine-grained PRs for everything I noticed.

**Comment by srittau** [comment]
@rchen152 @JelleZijlstra @Solumin Fron my perspective, we are basically done when the last three PRs go in. If you find the time, I would like to get the final "good to go" from you three:

* [ ] @rchen152 
* [ ] @JelleZijlstra 
* [ ] @Solumin 
* [x] @srittau

The next step is to find a sponsor and post the PEP to typing-sig. Maybe @gvanrossum would be willing to sponsor this PEP?

**Comment by gvanrossum** [comment]
I'll look into it. I haven't read the draft yet, and I would like to make sure that this also works for the people at Microsoft who are working on Pylance and Pyright. I know they have struggled with certain aspects of typeshed.

Also, what is happening to the ideas to split up typeshed into multiple installable packages? (IIRC @JukkaL was working on that.)

**Comment by srittau** [comment]
We should definitely ask the maintainers of the type checkers not involved here (pyright, pyre) to review the draft carefully when we post it to typing-sig.

**Comment by JukkaL** [comment]
> Also, what is happening to the ideas to split up typeshed into multiple installable packages?

It got delayed but I'm hoping that we can get back to it soon.

**Comment by Solumin** [comment]
I'm just waiting for #72 and #83 before reviewing.

**Comment by srittau** [comment]
Done. I merged them.

**Comment by Solumin** [comment]
Nits:
- "In addition, the self annotation can not contain type variable itself." is unclear.
- "An alias to a type may contain type variables, in which case all type variables must be substituted when the alias is used:" clarify that this is what PEP 484 requires.
- In Syntax section, we say to use `async` for coroutines, but Decorators section says to use `asyncio.coroutine`. Clarify this, e.g. decorator is allowed but encourage use of `async` keyword.

Should we revisit Python 3.7 as the required syntax version? That was decided a year and a half ago, and I'd really like to be able to use positional-only arguments in type stubs, because that _is_ something type checkers should be enforcing.

**Comment by rchen152** [comment]
I opened PR #85 with some hopefully uncontroversial edits to fix typos / improve flow. One more suggestion that may warrant some discussion:

For class bodies, `...` and `pass` are both listed as supported constructs with the style guide suggesting only using `...`, whereas for methods, `...` is listed as a supported construct and `pass` is undefined/unspecified. I think it would be better to say that `pass` is also unsupported for classes, as the current state seems a bit like unnecessary hair-splitting ("A and B are both allowed, but please never use B").

> Should we revisit Python 3.7 as the required syntax version?

I suspect it's actually pytype that's holding us back in this regard, since I don't have any recollection of adding support for positional-only arguments to our current pyi parser. (But this might something we get for free once we switch from our custom parser to typed_ast, which is happening any day now...)

**Comment by srittau** [comment]
> * "In addition, the self annotation can not contain type variable itself." is unclear.
> * "An alias to a type may contain type variables, in which case all type variables must be substituted when the alias is used:" clarify that this is what PEP 484 requires.
> * In Syntax section, we say to use `async` for coroutines, but Decorators section says to use `asyncio.coroutine`. Clarify this, e.g. decorator is allowed but encourage use of `async` keyword.

I try to address the first and last point in #86. Can you make a suggestion for the middle point?

> Should we revisit Python 3.7 as the required syntax version? That was decided a year and a half ago, and I'd really like to be able to use positional-only arguments in type stubs, because that _is_ something type checkers should be enforcing.

I would love to use the "proper" syntax, but I think we can't mandate it, until Python 3.6 is no longer supported (next year). I tried to backport the new syntax to typed-ast, but failed.

**Comment by Solumin** [comment]
> I try to address the first and last point in #86. Can you make a suggestion for the middle point?

"An alias to a type may contain type variables. As per PEP 484, all type variables must be substituted when the alias is used:"

> I would love to use the "proper" syntax, but I think we can't mandate it, until Python 3.6 is no longer supported (next year). I tried to backport the new syntax to typed-ast, but failed.

Since this PEP is intended as a living document, hopefully we can change this particular point soon.

**Comment by srittau** [comment]
> "An alias to a type may contain type variables. As per PEP 484, all type variables must be substituted when the alias is used:"

For simplicity's sake, I commited this directly.

**Comment by srittau** [comment]
I am a bit unsure how to proceed. I think we have all changes in that were requested and agreed on. What are our next steps? Posting this to typing-sig?

**Comment by Solumin** [comment]
The last couple PRs should be resolved, yes? After that, sending it to typing-sig is a good next step, I think: https://www.python.org/dev/peps/pep-0001/#submitting-a-pep

**Comment by srittau** [comment]
Obsolete as we're not planning to publish this as a PEP anymore.
