### ISSUE TITLE
Are type checkers free to deviate?

### ISSUE THREAD

**Issue by JelleZijlstra** [srittau/type-stub-pep#6]
https://github.com/srittau/type-stub-pep/wiki/PEP-Content currently says that "checkers are free to deviate". As a typeshed maintainer, I think I'd prefer a stronger recommendation. For me, the value of this PEP will be that we have a standard that type checkers have to follow, so that typeshed can be useful for all conformant type checkers. If type checkers are free to be more restrictive in what kinds of stubs they accept, it will be hard for them to make use of typeshed as a resource. Similarly, having a common standard for stubs will make it easier for authors of PEP 561 stub packages to write stubs that will be useful for multiple type checkers.

So I would prefer a stronger recommendation along the lines of "conformant type checkers should interpret stubs as described in this PEP, and stub authors who aim for compatibility should write stubs as described here". (Of course, there's nothing to stop Google or Dropbox from internally using stubs that work only with pytype or mypy.)

I'm curious to hear what others think.

**Comment by srittau** [comment]
On the stubs side, I definitely support wording to the effect that if an author uses features beyond those described in this PEP, the stub might get misinterpreted.

On the type checker side, I like the idea to call checkers that adhere to the PEP "conformant". But that begs two questions:
* Should conformant type checkers be allowed to support extra constructs?
* Must a type checker support all stub features described in the PEP to be called "conformant"? For example, can a type checker be called conformant if just treats properties as `Any`?

**Comment by JelleZijlstra** [comment]
Yes, I think type checkers should be allowed to support more constructs. I think this is important to encourage experimentation. However, experimental features shouldn't be allowed in cross-type checker stubs until there is a PEP update.

I think type checkers should "support" all stub features to the extent that they can parse all mandated features and not reject the stub as invalid. But they are free to fall back to Any internally for constructs they don't support.

**Comment by rchen152** [comment]
It sounds like instead of "checkers are free to deviate", we want something along the lines of "checkers are free to support additional constructs but should accept all the ones documented here."

**Comment by Solumin** [comment]
Having some very strict, very stripped-down reference stub checker would be necessary then, because there needs to be a way to ensure a stub conforms to this PEP and doesn't include additional constructs not supported by every type checker.

**Comment by JelleZijlstra** [comment]
I think that can be done easily with a linter, for example flake8-pyi.

**Comment by srittau** [comment]
I like the idea of a tool that checks stub files for conformity, ideally as part of a linter, but a stand-alone tool should not be too hard to implement, either.

**Comment by rchen152** [comment]
I updated the wiki page with the key points from this issue (clarification on deviating, conformity checker); we can probably close it now.
