### ISSUE TITLE
Author order

### ISSUE THREAD

**Issue by JelleZijlstra** [srittau/type-stub-pep#63]
I'm currently the first author in the draft, which doesn't make sense because clearly I haven't done the most to move the PEP forward. This matters somewhat because PEPs are cited (at least in other PEPs) to "First Author et al.".

I don't know what the exact order should be, but maybe we can make it alphabetical by last name, which would be Rebecca, Sebastian, Teddy, me.

**Comment by rchen152** [comment]
I wouldn't be opposed to that order, but I think Sebastian should be listed first if we're ordering by contribution level.
