### ISSUE TITLE
Docstrings in type stubs

### ISSUE THREAD

**Issue by gramster** [srittau/type-stub-pep#88]
This is a great document. I do have one concern though. Type stubs have use beyond just type checking, when used in editors/IDEs. For example, we use type stubs in Visual Studio Code to help us with autocomplete, when type inference is inadequate. Another use case for us in the editor is showing docstrings on hover. Where possible we will try to get these docstrings from .py source files; however, there are cases where that may be difficult. Extension modules is one case; another case is where docstrings may be dynamically generated, as is the case for many docstrings in pandas. In these cases we use docstrings in the stub files to fill in the gaps. I believe it would be better to just say that docstrings in stub files have no semantic effect, and not mandate that there are no docstrings (related, I don't see the reason for preferring ellipses over "pass" for function/method bodies).

**Comment by gvanrossum** [comment]
+1 on all the reasons why we might want docstrings in stubs. Obviously we can't mandate them (there are almost none in typeshed now).

I still prefer `...` over `pass`. This clarifies to the readers that they are reading a stub. But if there's a docstring we need neither.

**Comment by gramster** [comment]
You're right, I think we were adding them even in the presence of docstrings out of habit of still thinking of them as something other than code :-) (and when I said "related", the only relationship was "what comes after the docstring", but if its nothing, then there's no relationship).

I don't have strong feelings about the pass/... distinction, it just seems unnecessary and potentially confusing to say in some places either is fine but in other places one is preferred.

**Comment by srittau** [comment]
Maybe a bit of clarification: This PEP is informational and intended to document the status quo. It's also fairly conservative in the features it allows to leave design space for future extensions. For example, if a type checker wants to experiment with checked exceptions, it could take `pass` to mean "no exceptions thrown from this function". In fact, in the abstract we encourage tool authors to support additional constructs.

I would also really like to see docstrings in stub files. But as the status quo has stubs without docstrings, we decided to define it as "undefined" for now. This shouldn't prevent any tools from supporting them, though. And as this is intended to be a "living PEP", docstring support can be added when a consensus for that exists.

As a sneak peek, I have started working on a [stub extractor](/srittau/stub-extractor) that can extract type stubs from Python source files. It still needs a lot of work, but one of the optional features I want to implement is support for docstrings. And I want to  eventually supported C sources in some fashion. (Possibly via the argument clinic.)

(TLDR edit: +1 on docstrings, but preferably after the initial publishing of the PEP.)

**Comment by gvanrossum** [comment]
> This PEP is informational and intended to document the status quo. It's also fairly conservative in the features it allows to leave design space for future extensions.

Nevertheless users will take this PEP and write stubs that conform to it, and people will complain if stubs don't (based on my experience from PEP 8). So if the PEP says "currently stubs have no docstrings" people will not add docstrings to stubs even if it would be easy for them to do so, and they will even complain about stubs that don't have them.

All I'm saying is that we should be *very* careful with this PEP, and not lightly publish it. (Also, I still haven't had a gap in my schedule to read the whole thing. Sorry.)

**Comment by srittau** [comment]
> Nevertheless users will take this PEP and write stubs that conform to it, and people will complain if stubs don't (based on my experience from PEP 8).

That sounds like something I would do. :)

> (Also, I still haven't had a gap in my schedule to read the whole thing. Sorry.)

We started writing this PEP 2.5 years ago, we are in absolutely no hurry.

**Comment by rchen152** [comment]
What if we:
* Took out the two mentions of "Do not include docstrings".
* Changed this section:

> Using a function or method body other than the ellipsis literal is unspecified. Stub authors should avoid any other body, including ones consisting only of pass or a docstring if they want to ensure compatibility with all type checkers.

to something along the lines of:

> Using a function or method body other than the ellipsis literal is currently unspecified. Stub authors may experiment with other bodies, but it is up to individual type checkers how to interpret them.

Personally, I'm iffy on the idea of including docstrings in stubs (they're not type information, and they're meant for consumption by humans, not tooling), but I don't think we want to actively discourage experimentation with them, which it sounds like the current language would do.

**Comment by srittau** [comment]
@rchen152 I like your suggested wording.

**Comment by gramster** [comment]
@rchen152 , another way of thinking about stub files is as "the specification of the public API of a package or module". That's a broader interpretation and maybe controversial (as the files are "type stubs", not "API specs"), but it is a lens through which .pyi files could be viewed and one more consistent with including type stubs.

**Comment by erictraut** [comment]
Docstrings are most important to include in a stubs when there is no corresponding Python source code — e.g. when the implementation is written in C++. In those cases, there's no other source of docstrings for a static analyzer. Perhaps the PEP should make it clear that docstrings are highly encouraged in this case. We could leave it as noncommittal in other cases.

**Comment by JelleZijlstra** [comment]
This is similar to #92 in that it covers a different purpose for stub files than the one we've so far been familiar with (typing). I'm supportive of making stubs useful for that new purpose too, so I'd favor allowing docstrings in this PEP.

Separately we'll have to discuss whether to start including docstrings in typeshed.

**Comment by gvanrossum** [comment]
The quality, quantity and format of docstrings varies greatly across libraries (and even in the stdlib). For those cases where a developer chooses to include docstrings in a stub, should we recommend the stub docstrings be exactly the same as those in the actual code, or should we allow simplified docstrings that are appropriate for display in an IDE? Sometimes the code has very elaborate docstrings but I wouldn't want to see all of that in a pop-up window in my IDE (information overload). OTOH keeping the docstrings in the stubs identical to those in the code would simplify tooling to be developed to keep the docstrings in stubs up to date.

**Comment by srittau** [comment]
My gut feeling says that the docstrings in the stubs should match those in the implementation. One on the main reasons being that otherwise there is danger that the stub docstrings will not be updated when they should be. That said, I don't think we should put that in the PEP as long as there hasn't been experience with docstrings in stubs.

**Comment by srittau** [comment]
The wording has been updated now to allow docstrings.
