### ISSUE TITLE
Clarifying difference between `Any` and missing annotation

### ISSUE THREAD

**Issue by erictraut** [srittau/type-stub-pep#95]
The current draft says that “if an argument is unannotated, its type is assumed to be Any”. I recommend that we make a strong distinction between an unannotated type and `Any`. The former represents an incomplete type. The latter represents a type that was explicitly specified as `Any` by the author of the interface.

I don’t want to encourage stub authors to simply fill in a bunch of `Any` annotations out of laziness. That won't serve anyone well. Annotations should be omitted until someone has time to fill them in correctly.

Pyright distinguishes between these two and refers to the latter as “unknown”. When pyright’s “strict” mode is enabled, all uses of unknown types are flagged as errors, so if someone attempts to use a package whose types are partially unknown, that package will be difficult / painful to use with strict mode.

**Comment by srittau** [comment]
We already say "Do not use Any to mark unannotated arguments or return values", but it's a bit hidden away in the "Incomplete Stubs" section. I will update the wording in the "Functions and Methods" section as well. Do you have any suggestion for what to do with (module or class-level) attributes?

**Comment by erictraut** [comment]
Ah, I missed that statement. Yeah, making it more prominent would be good.

Module or class-level attributes could be declared without a type using the `x = ...` syntax. I'm thinking that's preferable to `x: Any` in most cases. What do you think?

**Comment by JelleZijlstra** [comment]
That could work, yes. In practice it seems unlikely that this would come up much for module-level attributes at least (it should be pretty easy to figure out what the type is).

**Comment by srittau** [comment]
I am leaving the class-level attributes out for now. Main reason is that mypy interprets `x` to have type `ellipsis` in the example `x = ...`, so it doesn't work at the moment.

**Comment by srittau** [comment]
I think this worded a bit better now.
