### ISSUE TITLE
Question about @type_check_only decorator

### ISSUE THREAD

**Issue by erictraut** [srittau/type-stub-pep#96]
The PEP talks about using the `@type_check_only` decorator. I don’t understand why this is needed. If a type is not available at runtime, it should not be part of the public interface of a library. It shouldn’t appear as an input parameter or a return type. For poorly-designed libraries that violate this rule, the stub could define a “dummy” type that begins with an underscore indicating that it’s private and shouldn’t be used by a caller. I can’t think of any other circumstance where a `@type_check_only` decorator would be needed. Am I missing something?

**Comment by JelleZijlstra** [comment]
It's currently unused in typeshed, so it doesn't seem like we need this decorator very much in practice. However, the motivating use case would be that you want to use the dummy type in user code (for example, to indicate that your function accepts the same type as the underlying library).

In any case, the function already exists in `typing` in the stdlib (https://docs.python.org/3/library/typing.html#typing.type_check_only). We could deprecate it, but that seems outside the scope of this PEP.

**Comment by erictraut** [comment]
My recommendation is that this PEP shouldn't discuss or promote the use of `@type_check_only`.

**Comment by srittau** [comment]
I honestly still like the idea of this decorator. While ideally a stub wouldn't need to define a stub-only class or protocol, in practice this is the case when describing existing libraries. Without this decorator there is no simple, standardized way to mark such classes. Instead, we should fix typeshed to use this decorator where necessary. (Or even better, convince upstream maintainers to include these classes in the implementation.)

**Comment by gvanrossum** [comment]
And yet there's not a single use of it in typeshed. We're not removing (or
even deprecating) it, we'd just not mention it in the recommendations,
based on minimal need.

**Comment by srittau** [comment]
While I'm still attached to the idea, I admit that it didn't gain traction so far. And following the idea that this PEP should follow the status quo, I have to admit that it makes sense to remove this.

**Comment by srittau** [comment]
This has been removed now.
